### ISSUE TITLE
FirebaseNamespace

### ISSUE THREAD

**Issue by DevJoseWeb** [codediodeio/angular-firestarter#65] opened 2018-07-20 02:51 UTC
// Sends email allowing user to reset password
  resetPassword(email: string) {
    const fbAuth = firebase.auth();

ERROR in src/app/core/auth.service.ts(48,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(53,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(58,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(63,35): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.
src/app/core/auth.service.ts(115,29): error TS2339: Property 'auth' does not exist on type 'FirebaseNamespace'.

ℹ ｢wdm｣: Failed to compile.

**Comment by schankam** [comment] 2018-07-23 13:50
Duplicate of #61

**Comment by DevJoseWeb** [comment] 2018-07-28 03:55
Tanks  schankam !

**Closed** 2018-08-11 14:16 UTC
